spring:
  data:
    mongodb:
      uri: mongodb://root:rhleh2160@mpr-documentdb.cxsescezqkce.ap-northeast-1.docdb.amazonaws.com:27017/mprDB?ssl=true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

