spring:
  data:
    mongodb:
      uri: mongodb://root:rhleh2160@mpr-documentdb.cxsescezqkce.ap-northeast-1.docdb.amazonaws.com:27017/mprDB?ssl=true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# java -jar build/libs/backend-0.0.1-SNAPSHOT.jar
# java  -DsslCertificate=./ssl/rds-combined-ca-bundle.pem -jar build/libs/backend-0.0.1-SNAPSHOT.jar
# java  -DsslCertificate=./ssl/rds-combined-ca-bundle.pem -DSPRING_DATA_MONGO_URI=mongodb://root:rhleh2160@mpr-documentdb.cxsescezqkce.ap-northeast-1.docdb.amazonaws.com:27017/mprDB?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&retryWrites=false -jar  build/libs/backend-0.0.1-SNAPSHOT.jar